### ISSUE TITLE
Unrecognized error: dictionary update sequence element

### ISSUE THREAD

**Issue by DAVIZINH0** [develop-dvs/domoticz-AirHumidifier2#3]
Hello.
I use this plugins since some weeks ago and works perfect.
today I update my docker container and have some errors.
The one that i cant solved is this:

Error: Python Plugin System: (Humidificador) Unrecognized error: dictionary update sequence element #0 has length 21; 2 is required

and not works the plugin :-(

**Comment by martkotur** [comment]
New system inslall on raspbery pi, DOMOTICS in system, Its error too. Don`t work on/off swich
Old installation on anothe rasp - no problem!

**Comment by DAVIZINH0** [comment]
dont work on/off, and sensors of the humidifier.
the miio library changes days ago because a library was deprecated.
maybe some adjust its necesary on this plugin

**Comment by DAVIZINH0** [comment]
@develop-dvs this plugin is amazing, can you help with this problem?

**Comment by zzaal** [comment]
I have the same problem
it happened after the update python-miio
I wrote to the developer, this is what he answered:
https://github.com/rytilahti/python-miio/issues/991
Can you help?

**Comment by DAVIZINH0** [comment]
the developer is missing :-(
i try to set the log of the plugin in debug but the information in domoticz not tell us more than the normal log :-(

**Comment by develop-dvs** [comment]
i reply in https://github.com/rytilahti/python-miio/issues/991

**Comment by develop-dvs** [comment]
fix! update miio and plugin from repo
